# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TemperatureService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18TemperatureService.proto\x12\x13temperature_service\"G\n\x05Query\x12\x11\n\x04\x64\x61te\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08location\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x07\n\x05_dateB\x0b\n\t_location\"B\n\x0bTemperature\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x10\n\x08location\x18\x02 \x01(\t\x12\x13\n\x0btemperature\x18\x03 \x01(\x01\"\x1d\n\x0bStatusReply\x12\x0e\n\x06status\x18\x01 \x01(\t\"M\n\x0fTemperatureList\x12:\n\x10temperature_data\x18\x01 \x03(\x0b\x32 .temperature_service.Temperature2\xc8\x01\n\x12TemperatureService\x12Y\n\x11\x43reatetemperature\x12 .temperature_service.Temperature\x1a .temperature_service.StatusReply\"\x00\x12W\n\x11SearchTemperature\x12\x1a.temperature_service.Query\x1a$.temperature_service.TemperatureList\"\x00\x42\x37\n\x1bio.grpc.examples.iotserviceB\x0fIoTServiceProtoP\x01\xa2\x02\x04TEMPb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TemperatureService_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033io.grpc.examples.iotserviceB\017IoTServiceProtoP\001\242\002\004TEMP'
  _QUERY._serialized_start=49
  _QUERY._serialized_end=120
  _TEMPERATURE._serialized_start=122
  _TEMPERATURE._serialized_end=188
  _STATUSREPLY._serialized_start=190
  _STATUSREPLY._serialized_end=219
  _TEMPERATURELIST._serialized_start=221
  _TEMPERATURELIST._serialized_end=298
  _TEMPERATURESERVICE._serialized_start=301
  _TEMPERATURESERVICE._serialized_end=501
# @@protoc_insertion_point(module_scope)
