# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import TemperatureService_pb2 as TemperatureService__pb2


class TemperatureServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Createtemperature = channel.unary_unary(
                '/temperature_service.TemperatureService/Createtemperature',
                request_serializer=TemperatureService__pb2.Temperature.SerializeToString,
                response_deserializer=TemperatureService__pb2.StatusReply.FromString,
                )
        self.SearchTemperature = channel.unary_unary(
                '/temperature_service.TemperatureService/SearchTemperature',
                request_serializer=TemperatureService__pb2.Query.SerializeToString,
                response_deserializer=TemperatureService__pb2.TemperatureList.FromString,
                )


class TemperatureServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Createtemperature(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchTemperature(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TemperatureServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Createtemperature': grpc.unary_unary_rpc_method_handler(
                    servicer.Createtemperature,
                    request_deserializer=TemperatureService__pb2.Temperature.FromString,
                    response_serializer=TemperatureService__pb2.StatusReply.SerializeToString,
            ),
            'SearchTemperature': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchTemperature,
                    request_deserializer=TemperatureService__pb2.Query.FromString,
                    response_serializer=TemperatureService__pb2.TemperatureList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'temperature_service.TemperatureService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TemperatureService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Createtemperature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/temperature_service.TemperatureService/Createtemperature',
            TemperatureService__pb2.Temperature.SerializeToString,
            TemperatureService__pb2.StatusReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchTemperature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/temperature_service.TemperatureService/SearchTemperature',
            TemperatureService__pb2.Query.SerializeToString,
            TemperatureService__pb2.TemperatureList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
